services:
  server:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: "mysql:lts"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wXvcs7B5NkBFYI337vWY