services:
  server:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: "mysql:lts"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wXvcs7B5NkBFYI337vWY
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=wXvcs7B5NkBFYI337vWY"]
      interval: 10s
      timeout: 5s
      retries: 5